knp_paginator:
    default_options:
        default_limit: 10
        distinct: true
        filter_field_name: filterField
        filter_value_name: filterValue
        page_name: page
        page_out_of_range: ignore
        sort_field_name: sort
        sort_direction_name: direction
    template:
        pagination: 'pagination/custom_pagination.html.twig'
